### ISSUE TITLE
Unable to open file if not writable

### ISSUE THREAD

**Issue by ebtfr** [greglund/fitantid#1]
Hi,
I tried to use the code but got an error as you try to open the file in write mode.
I had no write access to the file so turned line 373 of the main.c file from 
`   in = fopen(argv[1], "r+b");`
to
`   in = fopen(argv[1], "rb");`

And it works like a charm.
Best regards and happy new year !

**Comment by greglund** [comment]
Happy New Year, and thanks for the report!  The fix is now included in the subsequent release.
